### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wanderzirkus** [openchargemap/ocm-docs#6] opened 2019-01-21 17:30 UTC
Hi,

am I missing something or is there no documentation on the properties delivered by the json-response at all? I mean things like the meaning of "IsRecentlyVerified" and when exactly it is true or false.

BR,
Friedemann.

**Comment by webprofusion-chrisc** [comment] 2019-01-22 05:44
Hi, no you are correct there is no per-data-field documentation currently, it just hasn't been written. 

Looking at this, IsRecentlyVerified is true if there is a DateLastVerified value. So I'd look at the DateLastVerified field instead which is computed based on a combination of DateLastConfirmed (typically the last edit date, if it's within the last 6 months), or the latest User comment with a positive status type, or the date it was created  in the database (if within the last month). We don't actually have a button anywhere for 'I confirm this information is all present and correct', which would probably be the best way.

**Comment by webprofusion-chrisc** [comment] 2019-01-22 05:44
Leaving the issue open because we do need full API docs.

**Comment by wanderzirkus** [comment] 2019-01-22 09:17
Thanks, I can do some documentation on my side when I have spme spare time. :)

**Comment by webprofusion-chrisc** [comment] 2021-12-06 05:41
Closing. Our API documentation (and associated output models) are fairly well documented now:https://openchargemap.org/site/develop/api

Adjustments can be made by editing our API schema: https://github.com/openchargemap/ocm-docs/blob/master/Model/schema/ocm-api-schema.yaml

**Closed by webprofusion-chrisc** 2021-12-06 05:41 UTC
Labels: enhancement
